name: 'Hello World'
description: 'Greet someone'
inputs:
outputs:
runs:
  using: "composite"
  steps:
    - name: Find file
      run: ls /github && find / -name example.file && exit 1
      shell: bash
