name: 'Hello World'
description: 'Greet someone'
inputs:
outputs:
runs:
  using: "composite"
  steps:
    - name: Find file
      run: find / -name example.file
      shell: bash

    - name: Fail
      id: fail
      run: exit 1
      shell: bash
